# Generated by Django 3.2.25 on 2024-07-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('elevation', models.DecimalField(decimal_places=1, default=-999.9, max_digits=5)),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('gsn_flag', models.CharField(blank=True, choices=[('', 'non-GSN station or WMO Station number not available'), ('GSN', 'GSN station')], max_length=3)),
                ('hcn_crn_flag', models.CharField(blank=True, choices=[('', 'Not a member of the U.S. Historical Climatology or U.S. Climate Reference Networks'), ('HCN', 'U.S. Historical Climatology Network station'), ('CRN', 'U.S. Climate Reference Network or U.S. Regional Climate Network Station')], max_length=3)),
                ('wmo_id', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
